CREATE TABLE "actores" (
  "id_actor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "teleseries" (
  "id_teleserie" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "actores_reparto" (
  "id_reparto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_actor" int NOT NULL,
  "id_teleserie" int NOT NULL,
  "temporadas" int,
  "capitulos" int,
  "protagonico" boolean,
  "sueldo" int
);

ALTER TABLE "actores_reparto" ADD FOREIGN KEY ("id_actor") REFERENCES "actores" ("id_actor");

ALTER TABLE "actores_reparto" ADD FOREIGN KEY ("id_teleserie") REFERENCES "teleseries" ("id_teleserie");
